stages:
  - test
  - build

test:
  stage: test
  image: maven:latest
  artifacts:
    paths:
      - coder-gate/target
    reports:
      junit:
        - coder-gate/target/ProjectReports/TEST_*.xml
  script:
    - cd coder-gate
    - echo "Pipeline test started"
    - mvn verify
  tags:
    - Group19Runner
  only:
    - dev

build:
  stage: build
  image: maven:latest
  script:
    - cd coder-gate
    - echo "Building the pipeline"
    - mvn clean package
  artifacts:
    paths:
      - coder-gate/target
  tags:
    - Group19Runner
  only:
    - dev
